version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3111:3111'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_HTTP_PORT=3111
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - grafana-network
    deploy:
      placement:
        constraints: [node.hostname == k8s-master]

volumes:
  grafana_data:

networks:
  grafana-network:
    external: true
    name: Docker-Network
