global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nestjs-microservices'
    file_sd_configs:
      - files:
          - '/etc/prometheus/targets.json'
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [service]
        target_label: instance
